### PR TITLE
Fix #3135 Make Structured Commons feature work on the beta server

### PR DESCRIPTION
**Pull request by VitalyVPinchuk**
Added static strings for DEPICTS property for prod and beta flavours.

Fixes #3135 Make Structured Commons feature work on the beta server

Added to build.gradle  buildConfigField "String", "DEPICTS_PROPERTY" for both prod and beta flavors.
Changed variables names.

Tested BetaDebug and ProdDebug on emulator with API level 28.

### CODE REVIEW

**Review by vanshikaarora — COMMENTED** [review]
Hey @VitalyVPinchuk I tested your code in my phone.
I found that Depicts works in Beta flavor in the following :
- While navigating to Media Details from Explore
- Clicking on depictions from Media Details
- Searching of depictions from Search Activity
Good to see these changes.

However on clicking any item from Search Activity no depicted image is found. Can you please look into this. After this we will make the PR ready for merge :)

**Comment by VitalyVPinchuk** [comment]
Hi @vanshikaarora 
Sorry, I don't understand what you are talking about. Could you please give me more details?

**Comment by vanshikaarora** [comment]
Hi @VitalyVPinchuk  Could you please make depicts work in Search Activity items?
Here is how you can notice the change. In prod server
1. Go to Explore
2. Search for any entity (Ex:rabbit)
3. Navigate to items
4. select any item from the list
5. In prod flavor images related to the given item are visible for most of the items
However in Beta flavor no image was loaded for the depicted item. Can you please check this out
Thanks!

**Comment by VitalyVPinchuk** [comment]
Thanks! I'll check it

**Comment by VitalyVPinchuk** [comment]
Unfortunately, search activity most time doesn't work for me... very unstable and unpredictable

**Comment by VitalyVPinchuk** [comment]
@vanshikaarora please have a look
I've made minor changes to Media and MediaClient, and I think I fixed the issues which were the obstacle for me for reproducing the issue.
But those weren't related to the issue you are describing. Probably images you're clicking just don't have depiction tags.
Screenshot_20191016-134840
Screenshot_20191016-151932

**Comment by vanshikaarora** [comment]
Hey @VitalyVPinchuk this is a brief about what i was talking. Clicking on any of tese items does not loads images in beta flavor. However in prod flavor images are loaded. Could you please look into this as well. Thanks

Screenshot_20191017_125647

**Comment by VitalyVPinchuk** [comment]
Hello @vanshikaarora 
I've looked into the matter and came up with this:
The app gets items from `real wikidata` server but it tries to get corresponding images from `beta wikimedia` server.
Evidently, `beta wikimedia` may not have matches for items picked from `real wikidata`.

So we have to use either both beta or both real servers for such operations.

But @nicolas-raoul says https://github.com/commons-app/apps-android-commons/issues/3135#issuecomment-526436565 that `real wikidata` should be used.

**Comment by vanshikaarora** [comment]
@nicolas-raoul Can you please pitch in your suggestions here

**Comment by nicolas-raoul** [comment]
Ah yes, `real wikidata` items contain filenames for `real wikimedia commons`, so it won't work in beta.
I guess it is unavoidable.
When testing wikidata-related things, better use the `prod` flavor of the app.
I suggest making things work as far as possible, and giving up for Structured Commons features that can't possibly work with the beta server.

**Comment by VitalyVPinchuk** [comment]
Then this is it

**Comment by VitalyVPinchuk** [comment]
Hi!
Should there be any extra fixes?

**Comment by nicolas-raoul** [comment]
There might be a few other things that can be improved later, but I suggest merging for now.

**Comment by nicolas-raoul** [comment]
@VitalyVPinchuk By the way, if you have time, merging the latest master of https://github.com/commons-app/apps-android-commons into this branch would be wonderful :-) There will probably be some conflicts that need be be solved manually (and tested) before your work can be merged into master and released, your help on this would be really useful :-)

**Comment by nicolas-raoul** [comment]
@vanshikaarora If you have time I guess this PR can be tested then merged into your vanshikaarora:upload_caption_depict ? :-) (I have not tested though)

**Comment by VitalyVPinchuk** [comment]
> @VitalyVPinchuk By the way, if you have time, merging the latest master of https://github.com/commons-app/apps-android-commons into this branch would be wonderful :-) There will probably be some conflicts that need be be solved manually (and tested) before your work can be merged into master and released, your help on this would be really useful :-)

Sure I'll try, but there's a whole bunch of changes. It may take considerable amount of time.

**Comment by VitalyVPinchuk** [comment]
Probably @vanshikaarora might want to help me :)
There are tests that don't work and I don't know how to fix them.

**Comment by VitalyVPinchuk** [comment]
I think the PR is outdated and should be closed/discarded as other contributors are working on Structured Commons related improvements.

**Pull request closed without merging**
